#!/usr/bin/env bash
# R-014 truncation guardrail — block any .ts/.tsx file that ends mid-token.
#
# Background: Three commits in May 2026 silently truncated .ts files via the
# Edit tool (Patrick's 6813ddc, cook's ff86010, engineer's mid-DECISION-015
# pass). The Edit tool returns success even when the byte stream is cut off
# mid-attribute or mid-expression. tsc catches MOST of these, but only after
# CI burns build minutes and the developer has already pushed.
#
# This check is a one-line tripwire: every .ts/.tsx file under mobile/src/
# and mobile/app/ must end with a closing brace / paren / semicolon /
# comma / bracket plus a final newline. Files ending mid-identifier
# (`AGLIO_E_OLIO,` truncated to `AG`) or mid-comment get flagged.
#
# Runs in milliseconds. CI fails loudly; engineer recovers via the
# documented R-014 pattern (git show HEAD:<path> + re-apply edits).

set -euo pipefail

# Scope: only the files that ship in the app build. Exclude:
#   - node_modules
#   - .claude/worktrees (engineer scratch)
#   - docs/archive
#   - mobile/_test (test artifacts)
#   - mobile/.expo, mobile/android, mobile/ios (autogenerated)
#   - recipes-holding/ (per CLAUDE.md DECISION-013, not imported by the seeder)
#   - .d.ts declaration files (autogenerated; legitimately end with `>` or comment)
mapfile -t FILES < <(
  find mobile/src mobile/app -type f \( -name '*.ts' -o -name '*.tsx' \) 2>/dev/null \
    | grep -vE '/node_modules/|/\.claude/worktrees/|/recipes-holding/|/_test/|\.d\.ts$' \
    | sort
)

FAILED=()
for f in "${FILES[@]}"; do
  # Last meaningful character (skip trailing whitespace + newlines).
  LAST=$(tail -c 200 "$f" | tr -d '[:space:]' | tail -c 1)
  case "$LAST" in
    '}'|')'|';'|','|']')
      # OK — file ends with a balanced closing token.
      ;;
    '')
      # Truly empty file — allowed. Skip.
      ;;
    *)
      echo "❌ $f — last non-whitespace char is '${LAST}' (expected one of: } ) ; , ])"
      tail -c 120 "$f" | sed 's/^/   …/'
      echo ""
      FAILED+=("$f")
      ;;
  esac
done

if [ ${#FAILED[@]} -gt 0 ]; then
  echo "============================================================"
  echo "R-014 TRUNCATION GUARDRAIL: ${#FAILED[@]} file(s) failed."
  echo "Recover via:  git show HEAD:<path> > /tmp/clean.ts"
  echo "              compare + re-apply your edits + retry."
  echo "============================================================"
  exit 1
fi

echo "✅ R-014 truncation check: ${#FILES[@]} .ts/.tsx files all end on a balanced token."
